<a href="https://colab.research.google.com/github/GaganDeshbhandari/ml-project/blob/main/scripts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**READ EVERY TEXTS BELOW THE CELL**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Drive is now linked to this notebook can now access the drive to get the datasets


**NOTE : Always run the above cell before running any other cell because we need to link the Datasets from the Drive**

In [2]:
import pandas as pd
import os
import random

All the Libraries required for the project are imported in the above cell

In [3]:
BASE_PATH = '/content/drive/MyDrive/mini-project'
CLAIMS_DATA_PATH = os.path.join(BASE_PATH,'datasets/claims_datasets.csv')
USER_PERCEPTION_DATA = os.path.join(BASE_PATH,'datasets/user_perception_dataset.csv')

Paths for the datasets

In [4]:
claims_df = pd.read_csv(CLAIMS_DATA_PATH)
display(claims_df)

,claim_id,claim,ground_truth,source
0,1,India expanded 5G services to more tier-2 citi...,True,PIB Fact Check
1,2,UPI transactions reached record high monthly v...,True,PIB Fact Check
2,3,ISRO conducted successful test of reusable lau...,True,PIB Fact Check
3,4,Government extended free food grain scheme for...,True,PIB Fact Check
4,5,Digital payments usage increased significantly...,True,BOOM Live
...,...,...,...,...
116,117,Photo of crowded hospital shared without confi...,Mixture,BOOM Live
117,118,Message claims all bank accounts will be froze...,Mostly False,Alt News
118,119,Video of landslide shared as recent but actual...,Mostly False,BOOM Live
119,120,Government announced universal basic income fo...,False,Alt News
120,121,All private vehicles will be banned in metro c...,False,BOOM Live

Above cell displays the claims after reading from the Drive.

If its showing error make sure that you have executed the Drive Mounting and Library,Package importing cell

In [7]:

# claims = list(range(1, 32))  # claim_id 1 to 31
# users = [f"U{i}" for i in range(1, 21)]

# ratings_by_truth = {
#     "True": ["True"]*10 + ["Mostly True"]*7 + ["Mixture"]*3,
#     "Mostly True": ["Mostly True"]*9 + ["True"]*5 + ["Mixture"]*4 + ["Mostly False"]*2,
#     "Mixture": ["Mixture"]*8 + ["Mostly True"]*4 + ["Mostly False"]*4 + ["True"]*2 + ["False"]*2,
#     "Mostly False": ["Mostly False"]*9 + ["False"]*6 + ["Mixture"]*3 + ["Mostly True"]*2,
#     "False": ["False"]*10 + ["Mostly False"]*7 + ["Mixture"]*3
# }

# claims_df = pd.read_csv(CLAIMS_DATA_PATH)

# rows = []

# for _, row in claims_df.iterrows():
#     truth = row["ground_truth"]
#     possible_ratings = ratings_by_truth[truth]

#     for user in users:
#         rows.append({
#             "claim_id": row["claim_id"],
#             "user_id": user,
#             "rating": random.choice(possible_ratings)
#         })

# perception_df = pd.DataFrame(rows)

# perception_df.to_csv(USER_PERCEPTION_DATA, index=False)

# print("perception_dataset.csv created")
# print(perception_df)

perception_dataset.csv created
      claim_id user_id        rating
0            1      U1          True
1            1      U2          True
2            1      U3   Mostly True
3            1      U4   Mostly True
4            1      U5   Mostly True
...        ...     ...           ...
2415       121     U16         False
2416       121     U17  Mostly False
2417       121     U18       Mixture
2418       121     U19  Mostly False
2419       121     U20  Mostly False

[2420 rows x 3 columns]

The above cell generates the Random User Perception Data based on the ground truth of the Claims.

So that if the Claim is True most of the users will think that it is actually True.
And if the Claim is False most of the users will think that it is actually False.

And if the Claim is Mixture or Mostly True or Mostly False user perception changes randomly


**NOTE :** **THE ABOVE CELL IS EXECUTED ONLY ONCE BECAUSE IF EXECUTED ONCE MORE THE USER_PERCEPTION_DATA GETS REPLACED.**

**THATS WHY I HAVE COMMENTED IT**

In [8]:
user_perception_df = pd.read_csv(USER_PERCEPTION_DATA)
display(user_perception_df)

      claim_id user_id        rating
0            1      U1          True
1            1      U2          True
2            1      U3   Mostly True
3            1      U4   Mostly True
4            1      U5   Mostly True
...        ...     ...           ...
2415       121     U16         False
2416       121     U17  Mostly False
2417       121     U18       Mixture
2418       121     U19  Mostly False
2419       121     U20  Mostly False

[2420 rows x 3 columns]

The above cell displays the User_perception_data